export default init_flashcard = [
    { word: "Dog", translation: "Chó" },
    { word: "Cat", translation: "Mèo" },
    { word: "Apple", translation: "Táo" },
    { word: "Banana", translation: "Chuối" },
    { word: "Car", translation: "Xe hơi" },
    { word: "Book", translation: "Sách" },
    { word: "House", translation: "Nhà" },
    { word: "Hello", translation: "Xin chào" },
    { word: "Goodbye", translation: "Tạm biệt" },
    { word: "Friend", translation: "Bạn bè" },
    { word: "Love", translation: "Yêu" },
    { word: "Water", translation: "Nước" },
    { word: "Food", translation: "Thức ăn" },
    { word: "Phone", translation: "Điện thoại" },
    { word: "Computer", translation: "Máy tính" },
    { word: "Music", translation: "Âm nhạc" },
    { word: "Movie", translation: "Phim" },
    { word: "Time", translation: "Thời gian" },
    { word: "Money", translation: "Tiền" },
    { word: "Table", translation: "Cái bàn" },
  ];